name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Lay source code
        uses: actions/checkout@v6

      - name: In thong bao
        run: echo "Hello GitHub Actions"

      - name: Kiem tra Java
        run: java -version

      - name: Xem thu muc
        run: ls -la